export const CAT_DEFS = [
  { id: 'bills', name: 'Bills' },
  { id: 'books', name: 'Books' },
  { id: 'cars', name: 'Cars' },
  { id: 'cash', name: 'Cash' },
  { id: 'clothes', name: 'Clothes' },
  { id: 'communication', name: 'Communication' },
  { id: 'crypto', name: 'Crypto' },
  { id: 'digital', name: 'Digital' },
  { id: 'eating_out', name: 'Eating out' },
  { id: 'education', name: 'Education' },
  { id: 'entertainment', name: 'Entertainment' },
  { id: 'food', name: 'Food' },
  { id: 'junk', name: 'Junk' },
  { id: 'gadgets', name: 'Gadgets' },
  { id: 'gifts', name: 'Gifts' },
  { id: 'games', name: 'Games' },
  { id: 'fuel', name: 'Fuel' },
  { id: 'health', name: 'Health' },
  { id: 'hobbies', name: 'Hobbies' },
  { id: 'house', name: 'House' },
  { id: 'job', name: 'Job' },
  { id: 'cart_riding', name: 'Cart riding' },
  { id: 'culture', name: 'Culture' },
  { id: 'medicine', name: 'Medicine' },
  { id: 'motorcycles', name: 'Motorcycles' },
  { id: 'furniture', name: 'Furniture' },
  { id: 'house_decoration', name: 'House decoration' },
  { id: 'unsure', name: "I don't know" },
  { id: 'insurance', name: 'Insurance' },
  { id: 'pets', name: 'Pets' },
  { id: 'family', name: 'Family' },
  { id: 'random', name: 'Random' },
  { id: 'relax', name: 'Relax' },
  { id: 'rent', name: 'Rent' },
  { id: 'sports', name: 'Sports' },
  { id: 'shooting_range', name: 'Shooting range' },
  { id: 'taxes', name: 'Taxes' },
  { id: 'taxi', name: 'Taxi' },
  { id: 'toiletry', name: 'Toiletry' },
  { id: 'transport', name: 'Transport' },
  { id: 'travel', name: 'Travel' },
  { id: 'tea', name: 'Tea' }
];

export const SWATCHES = ['#8a5a3b', '#3f6b52', '#b5432e', '#5c6e8a', '#a67c3d', '#6b4a6b', '#2f4d3a', '#7a6a4f'];

// Illustrative starter data so the ledger isn't empty on first launch.
// Dates are anchored relative to TODAY below — feel free to delete all
// via Settings > Danger Zone once you're ready to use your own data.
export const SEED = [
  [4.5, -0, 'food', 'Coffee'],
  [38.0, -0, 'fuel', 'Gas'],
  [62.3, -1, 'food', 'Groceries'],
  [24.0, -3, 'entertainment', 'Movie tickets'],
  [15.75, -6, 'medicine', 'Pharmacy'],
  [89.0, -5, 'bills', 'Electric bill'],
  [1200.0, -9, 'rent', 'Rent'],
  [54.0, -14, 'clothes', 'New shoes'],
  [46.2, -27, 'eating_out', 'Dinner out'],
  [1200.0, -40, 'rent', 'Rent'],
  [85.0, -53, 'entertainment', 'Concert'],
  [58.4, -63, 'food', 'Groceries'],
  [210.0, -85, 'cars', 'Car repair'],
  [1200.0, -101, 'rent', 'Rent'],
  [40.0, -120, 'sports', 'Gym membership'],
  [65.0, -155, 'gifts', 'Gift'],
  [95.0, -171, 'bills', 'Utilities'],
  [180.0, -200, 'gifts', 'Holiday shopping'],
  [310.0, -239, 'travel', 'Flight ticket'],
  [1200.0, -314, 'rent', 'Rent']
];

export const MONTHS = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];

export const MONTHS_BY_LANG = {
  en: MONTHS,
  sr: ['ЈАН', 'ФЕБ', 'МАР', 'АПР', 'МАЈ', 'ЈУН', 'ЈУЛ', 'АВГ', 'СЕП', 'ОКТ', 'НОВ', 'ДЕЦ'],
  ru: ['ЯНВ', 'ФЕВ', 'МАР', 'АПР', 'МАЙ', 'ИЮН', 'ИЮЛ', 'АВГ', 'СЕН', 'ОКТ', 'НОЯ', 'ДЕК']
};

export const CAT_NAMES_BY_LANG = {
  en: {
    bills: 'Bills',
    books: 'Books',
    cars: 'Cars',
    cash: 'Cash',
    clothes: 'Clothes',
    communication: 'Communication',
    crypto: 'Crypto',
    digital: 'Digital',
    eating_out: 'Eating out',
    education: 'Education',
    entertainment: 'Entertainment',
    food: 'Food',
    junk: 'Junk',
    gadgets: 'Gadgets',
    gifts: 'Gifts',
    games: 'Games',
    fuel: 'Fuel',
    health: 'Health',
    hobbies: 'Hobbies',
    house: 'House',
    job: 'Job',
    cart_riding: 'Cart riding',
    culture: 'Culture',
    medicine: 'Medicine',
    motorcycles: 'Motorcycles',
    furniture: 'Furniture',
    house_decoration: 'House decoration',
    unsure: "I don't know",
    insurance: 'Insurance',
    pets: 'Pets',
    family: 'Family',
    random: 'Random',
    relax: 'Relax',
    rent: 'Rent',
    sports: 'Sports',
    shooting_range: 'Shooting range',
    taxes: 'Taxes',
    taxi: 'Taxi',
    toiletry: 'Toiletry',
    transport: 'Transport',
    travel: 'Travel',
    tea: 'Tea'
  },
  sr: {
    bills: 'Рачуни',
    books: 'Књиге',
    cars: 'Аутомобили',
    cash: 'Готовина',
    clothes: 'Одећа',
    communication: 'Комуникације',
    crypto: 'Крипто',
    digital: 'Дигитално',
    eating_out: 'Изласци',
    education: 'Образовање',
    entertainment: 'Забава',
    food: 'Храна',
    junk: 'Ситнице',
    gadgets: 'Гаџети',
    gifts: 'Поклони',
    games: 'Игре',
    fuel: 'Гориво',
    health: 'Здравље',
    hobbies: 'Хобији',
    house: 'Кућа',
    job: 'Посао',
    cart_riding: 'Карт вожња',
    culture: 'Култура',
    medicine: 'Лекови',
    motorcycles: 'Мотоцикли',
    furniture: 'Намештај',
    house_decoration: 'Декорација',
    unsure: 'Не знам',
    insurance: 'Осигурање',
    pets: 'Кућни љубимци',
    family: 'Породица',
    random: 'Разно',
    relax: 'Опуштање',
    rent: 'Кирија',
    sports: 'Спорт',
    shooting_range: 'Стрелиште',
    taxes: 'Порези',
    taxi: 'Такси',
    toiletry: 'Хигијена',
    transport: 'Превоз',
    travel: 'Путовања',
    tea: 'Чај'
  },
  ru: {
    bills: 'Счета',
    books: 'Книги',
    cars: 'Машины',
    cash: 'Наличные',
    clothes: 'Одежда',
    communication: 'Связь',
    crypto: 'Крипто',
    digital: 'Цифровое',
    eating_out: 'Рестораны',
    education: 'Образование',
    entertainment: 'Развлечения',
    food: 'Еда',
    junk: 'Мелочи',
    gadgets: 'Гаджеты',
    gifts: 'Подарки',
    games: 'Игры',
    fuel: 'Топливо',
    health: 'Здоровье',
    hobbies: 'Хобби',
    house: 'Дом',
    job: 'Работа',
    cart_riding: 'Картинг',
    culture: 'Культура',
    medicine: 'Лекарства',
    motorcycles: 'Мотоциклы',
    furniture: 'Мебель',
    house_decoration: 'Декор',
    unsure: 'Не знаю',
    insurance: 'Страховка',
    pets: 'Питомцы',
    family: 'Семья',
    random: 'Разное',
    relax: 'Отдых',
    rent: 'Аренда',
    sports: 'Спорт',
    shooting_range: 'Тир',
    taxes: 'Налоги',
    taxi: 'Такси',
    toiletry: 'Гигиена',
    transport: 'Транспорт',
    travel: 'Путешествия',
    tea: 'Чай'
  }
};

export const I18N = {
  en: {
    subtitle: '— EXPENSE LEDGER —',
    totalSpent: 'TOTAL SPENT',
    today: 'TODAY',
    voidPrompt: 'VOID THIS ENTRY?',
    yes: 'YES',
    no: 'NO',
    navLedger: 'LEDGER',
    navChart: 'CHART',
    noEntries: '— no entries this period —',
    nothingToChart: '— nothing to chart —',
    newEntry: 'New Entry',
    amount: 'AMOUNT',
    date: 'DATE',
    category: 'CATEGORY',
    memo: 'MEMO (optional)',
    memoPlaceholder: 'what was it for?',
    newCatPlaceholder: 'category name',
    add: 'ADD',
    cancel: 'CANCEL',
    stampItIn: 'STAMP IT IN',
    newChip: '+ New',
    editEntry: 'Edit Entry',
    saveChanges: 'SAVE CHANGES',
    settingsTitle: 'Settings',
    language: 'Language',
    currency: 'Currency',
    data: 'Data',
    exportJson: 'Export JSON',
    exportCsv: 'Export CSV',
    importJson: 'Import JSON',
    importCsv: 'Import CSV',
    done: 'Save',
    conversionRate: 'Conversion Rate',
    perUsd: '1 USD =',
    dangerZone: 'Danger Zone',
    deleteAll: 'Delete All Data',
    deleteAllWarn: 'This permanently erases every entry and category you\u2019ve created. Type Yes to confirm.',
    typeYesPlaceholder: 'Type "Yes"',
    eraseEverything: 'ERASE EVERYTHING',
    addedToast: 'added',
    savedToast: 'Entry saved',
    periodDay: 'DAY',
    periodWeek: 'WEEK',
    periodMonth: 'MONTH',
    periodYear: 'YEAR',
    numberFormat: 'Number Format',
    thousandsSep: 'Thousands separator',
    thousandsChar: 'Separator character',
    decimalPlaces: 'Decimal places',
    decimalChar: 'Decimal character',
    on: 'ON',
    off: 'OFF',
    preview: 'Preview'
  },
  sr: {
    subtitle: '— ДНЕВНИК ТРОШКОВА —',
    totalSpent: 'УКУПНО ПОТРОШЕНО',
    today: 'ДАНАС',
    voidPrompt: 'ПОНИШТИ УНОС?',
    yes: 'ДА',
    no: 'НЕ',
    navLedger: 'ДНЕВНИК',
    navChart: 'ГРАФИКОН',
    noEntries: '— нема уноса за овај период —',
    nothingToChart: '— нема податка за графикон —',
    newEntry: 'Нови унос',
    amount: 'ИЗНОС',
    date: 'ДАТУМ',
    category: 'КАТЕГОРИЈА',
    memo: 'НАПОМЕНА (опционо)',
    memoPlaceholder: 'за шта је било?',
    newCatPlaceholder: 'назив категорије',
    add: 'ДОДАЈ',
    cancel: 'ОТКАЖИ',
    stampItIn: 'УПИШИ',
    newChip: '+ Ново',
    editEntry: 'Измени унос',
    saveChanges: 'САЧУВАЈ',
    settingsTitle: 'Подешавања',
    language: 'Језик',
    currency: 'Валута',
    data: 'Подаци',
    exportJson: 'Извези JSON',
    exportCsv: 'Извези CSV',
    importJson: 'Увези JSON',
    importCsv: 'Увези CSV',
    done: 'Сачувај',
    conversionRate: 'Курс размене',
    perUsd: '1 USD =',
    dangerZone: 'Опасна зона',
    deleteAll: 'Обриши све податке',
    deleteAllWarn: 'Ово трајно брише сваки унос и категорију. Укуцај Yes да потврдиш.',
    typeYesPlaceholder: 'Укуцај "Yes"',
    eraseEverything: 'ОБРИШИ СВЕ',
    addedToast: 'додато',
    savedToast: 'Унос сачуван',
    periodDay: 'ДАН',
    periodWeek: 'НЕДЕЉА',
    periodMonth: 'МЕСЕЦ',
    periodYear: 'ГОДИНА',
    numberFormat: 'Формат бројева',
    thousandsSep: 'Раздвајач хиљада',
    thousandsChar: 'Знак раздвајача',
    decimalPlaces: 'Децимална места',
    decimalChar: 'Децимални знак',
    on: 'ДА',
    off: 'НЕ',
    preview: 'Приказ'
  },
  ru: {
    subtitle: '— ЖУРНАЛ РАСХОДОВ —',
    totalSpent: 'ВСЕГО ПОТРАЧЕНО',
    today: 'СЕГОДНЯ',
    voidPrompt: 'АННУЛИРОВАТЬ ЗАПИСЬ?',
    yes: 'ДА',
    no: 'НЕТ',
    navLedger: 'ЖУРНАЛ',
    navChart: 'ГРАФИК',
    noEntries: '— нет записей за этот период —',
    nothingToChart: '— нечего показать —',
    newEntry: 'Новая запись',
    amount: 'СУММА',
    date: 'ДАТА',
    category: 'КАТЕГОРИЯ',
    memo: 'ЗАМЕТКА (опционально)',
    memoPlaceholder: 'на что потрачено?',
    newCatPlaceholder: 'название категории',
    add: 'ДОБАВИТЬ',
    cancel: 'ОТМЕНА',
    stampItIn: 'ЗАПИСАТЬ',
    newChip: '+ Новая',
    editEntry: 'Редактировать',
    saveChanges: 'СОХРАНИТЬ',
    settingsTitle: 'Настройки',
    language: 'Язык',
    currency: 'Валюта',
    data: 'Данные',
    exportJson: 'Экспорт JSON',
    exportCsv: 'Экспорт CSV',
    importJson: 'Импорт JSON',
    importCsv: 'Импорт CSV',
    done: 'Сохранить',
    conversionRate: 'Курс обмена',
    perUsd: '1 USD =',
    dangerZone: 'Опасная зона',
    deleteAll: 'Удалить все данные',
    deleteAllWarn: 'Это навсегда удалит все записи и категории. Введите Yes для подтверждения.',
    typeYesPlaceholder: 'Введите "Yes"',
    eraseEverything: 'УДАЛИТЬ ВСЁ',
    addedToast: 'добавлено',
    savedToast: 'Запись сохранена',
    periodDay: 'ДЕНЬ',
    periodWeek: 'НЕДЕЛЯ',
    periodMonth: 'МЕСЯЦ',
    periodYear: 'ГОД',
    numberFormat: 'Формат чисел',
    thousandsSep: 'Разделитель тысяч',
    thousandsChar: 'Символ разделителя',
    decimalPlaces: 'Знаков после запятой',
    decimalChar: 'Символ разделителя дробной части',
    on: 'ВКЛ',
    off: 'ВЫКЛ',
    preview: 'Пример'
  }
};
